<?php

return [

    'sumut_iii' => [

        'Kota Pematangsiantar' => [
            'Siantar Barat',
            'Siantar Timur',
            'Siantar Selatan',
            'Siantar Utara',
            'Siantar Martoba',
            'Siantar Marihat',
            'Siantar Marimbun',
            'Siantar Sitalasari',
        ],

        'Kabupaten Simalungun' => [
            'Bandar',
            'Bandar Huluan',
            'Bandar Masilam',
            'Bosar Maligas',
            'Dolok Batu Nanggar',
            'Dolok Masagal',
            'Dolok Panribuan',
            'Dolok Pardamean',
            'Dolok Silau',
            'Girsang Sipangan Bolon',
            'Gunung Malela',
            'Gunung Maligas',
            'Haranggaol Horison',
            'Hatonduhan',
            'Huta Bayu Raja',
            'Jawa Maraja Bah Jambi',
            'Jorlang Hataran',
            'Panei',
            'Panombeian Panei',
            'Pematang Bandar',
            'Pematang Sidamanik',
            'Pematang Silimahuta',
            'Purba',
            'Raya',
            'Raya Kahean',
            'Siantar',
            'Sidamanik',
            'Silau Kahean',
            'Silimakuta',
            'Tanah Jawa',
            'Tapian Dolok',
            'Ujung Padang',
        ],

        'Kabupaten Batu Bara' => [
            'Air Putih',
            'Datuk Lima Puluh',
            'Datuk Tanah Datar',
            'Laut Tador',
            'Lima Puluh',
            'Lima Puluh Pesisir',
            'Medang Deras',
            'Nibung Hangus',
            'Sei Balai',
            'Sei Suka',
            'Talawi',
            'Tanjung Tiram',
        ],

        'Kabupaten Asahan' => [
            'Aek Kuasan',
            'Aek Ledong',
            'Aek Songsongan',
            'Air Batu',
            'Air Joman',
            'Bandar Pasir Mandoge',
            'Bandar Pulau',
            'Buntu Pane',
            'Kisaran Barat',
            'Kisaran Timur',
            'Meranti',
            'Pulau Rakyat',
            'Pulo Bandring',
            'Rahuning',
            'Rawang Panca Arga',
            'Sei Dadap',
            'Sei Kepayang',
            'Sei Kepayang Barat',
            'Sei Kepayang Timur',
            'Setia Janji',
            'Silau Laut',
            'Simpang Empat',
            'Teluk Dalam',
            'Tinggi Raja',
            'Tanjung Balai',
        ],

        'Kota Tanjungbalai' => [
            'Datuk Bandar',
            'Datuk Bandar Timur',
            'Sei Tualang Raso',
            'Tanjungbalai Selatan',
            'Tanjungbalai Utara',
            'Teluk Nibung',
        ],

        'Kabupaten Pakpak Bharat' => [
            'Kerajaan',
            'Pagindar',
            'Pergetteng-getteng Sengkut',
            'Salak',
            'Siempat Rube',
            'Sitellu Tali Urang Jehe',
            'Sitellu Tali Urang Julu',
            'Tinada',
        ],

        'Kabupaten Dairi' => [
            'Berampu',
            'Gunung Sitember',
            'Lae Parira',
            'Parbuluan',
            'Pegagan Hilir',
            'Sidikalang',
            'Siempat Nempu',
            'Siempat Nempu Hilir',
            'Siempat Nempu Hulu',
            'Silahisabungan',
            'Silima Pungga-Pungga',
            'Sitinjo',
            'Sumbul',
            'Tanah Pinem',
            'Tigalingga',
        ],

        'Kabupaten Tanah Karo' => [
            'Barusjahe',
            'Berastagi',
            'Dolat Rayat',
            'Juhar',
            'Kabanjahe',
            'Kutabuluh',
            'Laubaleng',
            'Mardingding',
            'Merdeka',
            'Merek',
            'Munte',
            'Naman Teran',
            'Payung',
            'Simpang Empat',
            'Tigabinanga',
            'Tiganderket',
            'Tigapanah',
        ],

        'Kabupaten Langkat' => [
            'Babalan',
            'Bahorok',
            'Batang Serangan',
            'Besitang',
            'Binjai',
            'Brandan Barat',
            'Gebang',
            'Hinai',
            'Kuala',
            'Kutambaru',
            'Padang Tualang',
            'Pangkalan Susu',
            'Pematang Jaya',
            'Salapian',
            'Sawit Seberang',
            'Secanggang',
            'Sei Bingai',
            'Sei Lepan',
            'Selesai',
            'Sirapit',
            'Stabat',
            'Tanjung Pura',
            'Wampu',
        ],

        'Kota Binjai' => [
            'Binjai Barat',
            'Binjai Kota',
            'Binjai Selatan',
            'Binjai Timur',
            'Binjai Utara',
        ],
    ],

];